[build]
  publish = "build"
  command = "python3 build_static.py"

[[redirects]]
  from = "/builder"
  to = "/builder/"
  status = 301

[[redirects]]
  from = "/academy"
  to = "/academy/"
  status = 301

[[redirects]]
  from = "/audit"
  to = "/audit/"
  status = 301

[[redirects]]
  from = "/library"
  to = "/library/"
  status = 301

[[redirects]]
  from = "/guide"
  to = "/guide/"
  status = 301

[[redirects]]
  from = "/template"
  to = "/template/"
  status = 301

[[redirects]]
  from = "/analytics"
  to = "/analytics/"
  status = 301

[[redirects]]
  from = "/contribute"
  to = "/contribute/"
  status = 301
