"""
Normalizer: Blue UAS raw records -> forge_blue_uas_cleared.json

Reads tools/mining/output/raw/blue_uas-*.jsonl
Writes DroneClear Components Visualizer/forge_blue_uas_cleared.json

Output schema:
{
  "$schema": "https://droneclear.ai/schemas/blue-uas-cleared-v1.json",
  "generated": "<iso8601>",
  "sources": ["bluelist.dcma.mil", "diu.mil"],
  "cleared_systems": [
    {"id","name","vendor","category","cleared_date","status","description","source_url"},
    ...
  ],
  "framework_components": [
    {"id","name","vendor","role","status","source_url"},
    ...
  ]
}

Dedup key: data.id (stable `blue_uas_<slug>` generated by the miner).
Empty input -> valid file with empty arrays, so downstream consumers
(compliance dashboard, manufacturer_status flags) never crash on missing data.
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path


RAW_DIR = Path("tools/mining/output/raw")
OUT_FILE = Path("DroneClear Components Visualizer/forge_blue_uas_cleared.json")


def load_raw() -> list[dict]:
    records: list[dict] = []
    if not RAW_DIR.exists():
        return records
    for p in sorted(RAW_DIR.glob("blue_uas-*.jsonl")):
        for line in p.read_text(encoding="utf-8").splitlines():
            try:
                records.append(json.loads(line))
            except json.JSONDecodeError:
                continue
    return records


def normalize(raw: list[dict]) -> dict:
    cleared: dict[str, dict] = {}
    framework: dict[str, dict] = {}
    sources: set[str] = set()

    for rec in raw:
        rtype = rec.get("record_type")
        data = rec.get("data") or {}
        rid = data.get("id")
        url = rec.get("url") or ""
        if url:
            # Extract bare host
            try:
                host = url.split("/")[2]
                sources.add(host)
            except IndexError:
                pass
        if not rid:
            continue

        if rtype == "cleared_system":
            cleared[rid] = {
                "id": rid,
                "name": data.get("name", ""),
                "vendor": data.get("vendor", ""),
                "category": data.get("category", ""),
                "cleared_date": data.get("cleared_date", ""),
                "status": data.get("status", "cleared"),
                "description": data.get("description", ""),
                "source_url": data.get("source_url") or url,
            }
        elif rtype == "framework_component":
            framework[rid] = {
                "id": rid,
                "name": data.get("name", ""),
                "vendor": data.get("vendor", ""),
                "role": data.get("role") or data.get("category", ""),
                "status": data.get("status", "framework"),
                "source_url": data.get("source_url") or url,
            }
        # meta_jsrendered / meta_links are diagnostic only — skip

    return {
        "$schema": "https://droneclear.ai/schemas/blue-uas-cleared-v1.json",
        "generated": datetime.utcnow().isoformat() + "Z",
        "sources": sorted(sources),
        "cleared_count": len(cleared),
        "framework_count": len(framework),
        "cleared_systems": sorted(cleared.values(), key=lambda r: (r["vendor"].lower(), r["name"].lower())),
        "framework_components": sorted(framework.values(), key=lambda r: (r["vendor"].lower(), r["name"].lower())),
    }


def main():
    raw = load_raw()
    out = normalize(raw)
    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text(json.dumps(out, indent=2), encoding="utf-8")
    print(
        f"wrote {OUT_FILE}: {out['cleared_count']} cleared systems, "
        f"{out['framework_count']} framework components from {len(raw)} raw records"
    )


if __name__ == "__main__":
    main()
