// Real Chromium MediaRecorder and IndexedDB, with synthetic video and upstream
// MAVLink fixtures. No vehicle or external account is connected.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require('playwright'),E=require('../forge-source/session-evidence.js'),Lab=require('../forge-source/test-lab.js');
const fixtures=require('./fixtures/session_mavlink.json').fixtures;
const directory=path.resolve(process.argv[2]||'build');
(async()=>{
 const posts=[],server=http.createServer((req,res)=>{if(req.method!=='GET'){posts.push(req.url);res.writeHead(405);res.end();return;}const u=new URL(req.url,'http://localhost'),p=path.resolve(directory,'.'+decodeURIComponent(u.pathname)+(u.pathname.endsWith('/')?'index.html':''));if(!p.startsWith(directory+path.sep)||!fs.existsSync(p)||!fs.statSync(p).isFile()){res.writeHead(404);res.end();return;}const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.webmanifest':'application/manifest+json','.svg':'image/svg+xml','.zip':'application/zip','.txt':'text/plain'};res.writeHead(200,{'Content-Type':types[path.extname(p)]||'application/octet-stream','Cache-Control':'no-cache'});res.end(fs.readFileSync(p));});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin='http://127.0.0.1:'+server.address().port;let browser;
 try{
  browser=await chromium.launch({headless:true,...(process.env.AUDIT_CHROMIUM?{executablePath:process.env.AUDIT_CHROMIUM}:{})});
  const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
  await context.route('**/*',route=>new URL(route.request().url()).origin===origin?route.continue():route.abort());
  await context.addInitScript(()=>{
   function video(label){const c=document.createElement('canvas');c.width=640;c.height=360;const x=c.getContext('2d');function draw(){x.fillStyle='#173517';x.fillRect(0,0,640,360);x.fillStyle='#f3cd72';x.font='32px sans-serif';x.fillText(label+' '+performance.now().toFixed(0),40,180);}draw();setInterval(draw,80);return c.captureStream(12);}
   Object.defineProperty(navigator.mediaDevices,'getDisplayMedia',{value:async()=>video('Screen fixture')});Object.defineProperty(navigator.mediaDevices,'getUserMedia',{value:async()=>video('Camera fixture')});
   Object.defineProperty(navigator,'serial',{value:{requestPort:async()=>({readable:new ReadableStream({start(c){window.telemetryFixture=c;}}),open:async()=>{},close:async()=>{}})}});
  });
  const page=await context.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto(origin+'/session-recorder/');await page.waitForFunction(()=>document.querySelector('#rec-status').textContent.startsWith('Ready.'));
  await page.locator('#session-title').fill('PRIVATE-FIXTURE session <img src=x onerror="window.injected=true">');
  await page.locator('#session-aircraft').fill('PX4 simulator / test controller');await page.locator('#session-firmware').fill('fixture-build-123');await page.locator('#session-stack').selectOption('px4');await page.locator('#session-test-mode').selectOption('sitl');await page.locator('#session-expected').fill('Mission should become active');await page.locator('#session-steps').fill('1. Start simulation\n2. Select Mission');
  await page.locator('#choose-screen').click();await page.waitForFunction(()=>document.querySelector('#screen-preview').srcObject);
  await page.locator('#choose-camera').click();await page.waitForFunction(()=>document.querySelector('#camera-preview').srcObject);
  await page.locator('#connect-serial').click();await page.waitForFunction(()=>window.telemetryFixture);
  await page.evaluate(hex=>window.telemetryFixture.enqueue(Uint8Array.from(hex.match(/../g).map(b=>parseInt(b,16)))),fixtures.find(f=>f.name==='HEARTBEAT'&&f.wire_version===2).hex);await page.waitForFunction(()=>document.querySelector('#live-observation').textContent.includes('reports armed'));
  await page.locator('#start-recording').click();await page.waitForFunction(()=>!document.querySelector('#mark-event').disabled);
  await page.evaluate(hex=>{window.telemetryFixture.enqueue(Uint8Array.from(hex.match(/../g).map(b=>parseInt(b,16))));},fixtures.find(f=>f.name==='HEARTBEAT'&&f.wire_version===2).hex);
  await page.locator('#marker-note').fill('PRIVATE-FIXTURE problem <script>window.injected=true</script>');await page.locator('#mark-event').click();
  await page.waitForTimeout(1600);await page.locator('#stop-recording').click();await page.waitForFunction(()=>document.querySelector('#rec-status').textContent.startsWith('Saved locally.'),{timeout:20000});
  assert.match(await page.locator('#session-summary').innerText(),/1 supported MAVLink/);assert.equal(await page.locator('#saved-sessions option').count(),2);assert.equal(await page.evaluate(()=>Boolean(window.injected)),false);
  await page.locator('#session-actual').fill('The vehicle remained in Hold');await page.locator('#save-details').click();await page.waitForFunction(()=>!document.querySelector('#attach-log').disabled);
  await page.locator('#attach-log').setInputFiles([{name:'original.ulg',mimeType:'application/octet-stream',buffer:Buffer.from([85,76,111,103,1,18,53,0])},{name:'original.params',mimeType:'text/plain',buffer:Buffer.from('1\t1\tTEST_PARAM\t123\t6\n')}]);await page.waitForFunction(()=>document.querySelector('#evidence-files').textContent.includes('original.params'));
  await page.locator('#report-destination').selectOption('jira');assert.equal(JSON.parse(await page.locator('#report-preview').innerText()).type,'doc');await page.locator('#report-destination').selectOption('px4');assert.match(await page.locator('#report-preview').innerText(),/ver all/);
  await page.locator('#alignment-settings summary').click();await page.locator('#screen-offset').fill('0.4');await page.locator('#save-alignment').click();await page.waitForFunction(()=>document.querySelector('#rec-status').textContent.startsWith('Manual alignment saved.'));await page.locator('#timeline-position').evaluate(v=>{v.value='1';v.dispatchEvent(new Event('input',{bubbles:true}));});assert.ok(Math.abs(await page.locator('#screen-replay').evaluate(v=>v.currentTime)-0.6)<0.05);await page.locator('#play-session').click();await page.waitForTimeout(250);assert.ok(await page.locator('#screen-replay').evaluate(v=>v.currentTime)>0.6);await page.locator('#play-session').click();
  const catalogBytes=fs.readFileSync(path.join(directory,'system-tests/profiles.json')),catalog=JSON.parse(catalogBytes);
  const labReport={schema_version:1,tool:'forge-system-test-lab',tool_version:catalog.version,profile:'gauntlet',profile_version:catalog.version,catalog_sha256:await E.sha256(catalogBytes),config_sha256:'b'.repeat(64),recorded_at:'2026-10-07T12:00:00Z',system:{name:'fixture',version:'1',source_commit:'a'.repeat(40)},scope:'local_software_preparation',certification:false,program_acceptance:false,commands_executed:false,results:Lab.checks(catalog,'gauntlet').map(r=>({id:r.id,kind:r.kind,status:r.kind==='external'?'external_required':r.kind==='review'?'review_required':'blocked',detail:'Fixture result',evidence:[]}))};
  await page.locator('#attach-report').setInputFiles({name:'lab.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(labReport))});await page.waitForFunction(()=>document.querySelector('#attachment-status').textContent.includes('lab.json'));assert.ok((await page.locator('#report-preview').innerText()).includes('external\\_required'));
  const badGate=structuredClone(labReport);badGate.results.find(r=>r.kind==='external').status='pass';await page.locator('#attach-report').setInputFiles({name:'bad-gate.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(badGate))});await page.waitForFunction(()=>document.querySelector('#rec-status').textContent.includes('external'));assert.doesNotMatch(await page.locator('#evidence-files').innerText(),/bad-gate.json/);
  assert.equal(await page.locator('#send-slack').isEnabled(),false);assert.equal(posts.length,0);
  let promise=page.waitForEvent('download');await page.locator('#download-session').click();const downloaded=await promise,bundleBytes=new Uint8Array(fs.readFileSync(await downloaded.path())),parsed=await E.verifyBundle(bundleBytes);
  assert.ok(parsed.files.get('screen.webm')?.length>100);assert.ok(parsed.files.get('camera.webm')?.length>100);assert.ok(parsed.files.get('telemetry.tlog')?.length>8);assert.equal(parsed.session.test_outcome,'not_run');assert.equal(parsed.session.certification,false);assert.equal(parsed.session.files.filter(f=>f.role==='log').length,2);
  assert.equal(parsed.session.files.find(f=>f.role==='screen').alignment_offset_ms,400);assert.ok(parsed.files.has('telemetry-receipts.jsonl'));assert.equal(parsed.session.test_reports[0].claims_verified,false);assert.ok(parsed.session.test_reports[0].counts.external_required>0);
  assert.ok(await page.locator('.developer-only').first().isHidden());await page.locator('button[data-view="developer"]').click();assert.ok(await page.locator('.developer-only').first().isVisible());
  await page.reload();await page.waitForFunction(()=>document.querySelector('#rec-status').textContent.startsWith('Ready.'));await page.locator('#saved-sessions').selectOption(parsed.session.id);await page.locator('#open-saved').click();await page.waitForFunction(()=>document.querySelector('#rec-status').textContent==='Opened local session.');
  await page.locator('#open-bundle').setInputFiles({name:'session.zip',mimeType:'application/zip',buffer:Buffer.from(bundleBytes)});await page.waitForFunction(()=>document.querySelector('#rec-status').textContent.startsWith('Imported session.'));assert.equal(await page.locator('#saved-sessions option').count(),3);
  const before=await page.locator('#session-summary').innerText();const bad=bundleBytes.slice();bad[60]^=1;await page.locator('#open-bundle').setInputFiles({name:'bad.zip',mimeType:'application/zip',buffer:Buffer.from(bad)});await page.waitForFunction(()=>document.querySelector('#rec-status').textContent.includes('checksum')||document.querySelector('#rec-status').textContent.includes('Invalid'));assert.equal(await page.locator('#session-summary').innerText(),before);
  for(const width of [320,390,1440]){await page.setViewportSize({width,height:1000});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Reflow at '+width);}
  fs.mkdirSync('.local/design-review',{recursive:true});await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'.local/design-review/session-recorder-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:'.local/design-review/session-recorder-mobile.png',fullPage:true});
  // A new capture interrupted by closing the page retains committed chunks.
  await page.locator('#choose-screen').click();await page.locator('#start-recording').click();await page.waitForTimeout(1200);await page.close();const recovered=await context.newPage();recovered.on('pageerror',e=>errors.push(e.message));await recovered.goto(origin+'/session-recorder/');await recovered.waitForFunction(()=>document.querySelector('#rec-status').textContent.startsWith('Ready.'));const interrupted=await recovered.locator('#saved-sessions option').evaluateAll(options=>options.find(o=>o.textContent.includes('interrupted capture'))?.value);assert.ok(interrupted);await recovered.locator('#saved-sessions').selectOption(interrupted);await recovered.locator('#open-saved').click();await recovered.waitForFunction(()=>document.querySelector('#rec-status').textContent==='Opened local session.');assert.match(await recovered.locator('#session-summary').innerText(),/interrupted/);
  await recovered.evaluate(async()=>{await navigator.serviceWorker.ready;});await recovered.waitForFunction(()=>navigator.serviceWorker.controller);await context.setOffline(true);await recovered.reload();await recovered.waitForFunction(()=>document.querySelector('#rec-status').textContent.startsWith('Ready.'));await context.setOffline(false);
  assert.equal(errors.length,0,errors.join('\n'));assert.equal(posts.length,0,'Capture, notes and attachments never leave the device');
  await context.close();console.log('Recorder browser checks passed: real media encoding, MAVLink, IndexedDB, replay, multiple originals, reports, ZIP roundtrip/tamper, recovery, offline and responsive layout.');
 }finally{if(browser)await browser.close();await new Promise(resolve=>server.close(resolve));}
})().catch(error=>{console.error(error);process.exitCode=1;});
