const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),crypto=require('node:crypto');
const {checks,validateReport,validateReview}=require('../forge-source/test-lab.js');
const bytes=fs.readFileSync(require('node:path').resolve(__dirname,'../forge-source/system-tests/profiles.json'));
const catalog=JSON.parse(bytes),hash=crypto.createHash('sha256').update(bytes).digest('hex');
function fixture(profile='general') {return {schema_version:1,tool:'forge-system-test-lab',tool_version:catalog.version,profile,profile_version:catalog.version,catalog_sha256:hash,config_sha256:'b'.repeat(64),recorded_at:'2026-10-07T12:00:00Z',system:{name:'fixture',version:'1',source_commit:'a'.repeat(40)},scope:'local_software_preparation',certification:false,program_acceptance:false,commands_executed:false,results:checks(catalog,profile).map(row=>({id:row.id,kind:row.kind,status:row.kind==='external'?'external_required':row.kind==='review'?'review_required':'blocked',detail:'Fixture result',evidence:[]}))};}
test('all profiles retain general checks and have unique IDs',()=>{for(const profile of ['general','gauntlet','dow']) {const list=checks(catalog,profile);assert.equal(new Set(list.map(x=>x.id)).size,list.length);assert.deepEqual(list.slice(0,9),catalog.profiles.general.checks);assert.equal(validateReport(fixture(profile),catalog,hash).profile,profile);}});
test('wrong source/profile/version and qualification claims are rejected',()=>{for(const [key,value] of [['catalog_sha256','c'.repeat(64)],['profile','__proto__'],['profile_version','future'],['program_acceptance',true],['certification',true],['scope','official_acceptance']]){const r=fixture();r[key]=value;assert.throws(()=>validateReport(r,catalog,hash));}});
test('duplicates, missing rows and unsupported statuses are rejected',()=>{for(const mutate of [r=>r.results.pop(),r=>r.results[1]=r.results[0],r=>r.results[0].status='certified']){const r=fixture();mutate(r);assert.throws(()=>validateReport(r,catalog,hash));}});
test('human and external gates cannot be converted to passes',()=>{for(const profile of ['general','gauntlet','dow'])for(const kind of ['review','external']){const r=fixture(profile),row=r.results.find(x=>x.kind===kind);if(row){row.status='pass';assert.throws(()=>validateReport(r,catalog,hash));}}});
test('command passes need executed commands and evidence',()=>{const r=fixture(),row=r.results.find(x=>x.kind==='command');row.status='pass';assert.throws(()=>validateReport(r,catalog,hash));r.commands_executed=true;assert.throws(()=>validateReport(r,catalog,hash));row.evidence=[{adapter_output_sha256:'d'.repeat(64)}];assert.equal(validateReport(r,catalog,hash),r);row.evidence[0].raw_output='private';assert.throws(()=>validateReport(r,catalog,hash));});
test('saved reviews retain notes without elevating claims or accepting unknown check IDs',()=>{const review={schema_version:1,tool:'forge-test-review',profile:'general',profile_version:catalog.version,catalog_sha256:hash,certification:false,program_acceptance:false,report_verified:false,runner_report:fixture(),reviewer_notes:{G01:'Review note'}};assert.equal(validateReview(review,catalog,hash).reviewer_notes.G01,'Review note');review.reviewer_notes.unknown='Injected';assert.throws(()=>validateReview(review,catalog,hash));delete review.reviewer_notes.unknown;review.report_verified=true;assert.throws(()=>validateReview(review,catalog,hash));});
test('pinned RFS passes require the exact reviewed source digest',()=>{const r=fixture('gauntlet'),row=r.results.find(x=>x.id==='Q01');row.status='pass';row.evidence=[{path:'rfs.pdf',sha256:'c'.repeat(64)}];assert.throws(()=>validateReport(r,catalog,hash));row.evidence[0].sha256=catalog.profiles.gauntlet.checks[0].expected_sha256;assert.equal(validateReport(r,catalog,hash),r);});
