"""
ArduPilot .param file generator.

Takes a component selection (frame, FC, ESC, motors, battery, GPS) from the
Forge database and generates a base ArduPilot parameter file with sane defaults
for that specific hardware combination.

Usage:
    python tools/param_generator/generate.py --frame FRM-1005 --fc FC-1000 \
        --esc ESC-1001 --motor MTR-1000 --battery BAT-1009 --gps GPS-1009

    python tools/param_generator/generate.py --build "Apex Freestyle 5\""
        (looks up platform by name, uses its component relations)

    python tools/param_generator/generate.py --interactive
        (guided selection from the database)

Output: .param file (ArduPilot format: NAME,VALUE one per line)

The generator maps component specs to ArduPilot parameters:
  Frame   → FRAME_CLASS, FRAME_TYPE
  FC/IMU  → INS_*, SERIAL port assignments
  ESC     → MOT_PWM_TYPE, SERVO_DSHOT_*, INS_HNTCH_* (RPM filter)
  Motor   → MOT_SPIN_MIN/MAX, MOT_THST_EXPO, PID starting points
  Battery → BATT_CAPACITY, BATT_MONITOR, voltage thresholds
  GPS     → GPS_TYPE, GPS_AUTO_CONFIG, serial assignment
"""

from __future__ import annotations

import json
import sys
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Optional


DB_PATH = Path(__file__).resolve().parents[2] / "DroneClear Components Visualizer" / "forge_database.json"


# ── ArduPilot constants ─────────────────────────────────────────────────────

# FRAME_CLASS values
FRAME_CLASS = {
    "quad": 1, "hexa": 2, "octa": 3, "octa_quad": 4,
    "y6": 5, "heli": 6, "tri": 7, "single_copter": 8,
    "coax": 9, "bicopter": 10, "dodeca_hexa": 12,
}

# FRAME_TYPE values (for quads)
FRAME_TYPE = {
    "plus": 0, "x": 1, "v": 2, "h": 3, "v-tail": 15,
    "true-x": 1, "true_x": 1, "wide-x": 1, "dead-cat": 12,
    "betaflight-x": 12, "bf-x": 12, "squish-x": 18,
}

# MOT_PWM_TYPE based on ESC firmware/protocol
PWM_TYPE = {
    "pwm": 0, "oneshot": 1, "oneshot125": 2, "brushed": 3,
    "dshot150": 4, "dshot300": 5, "dshot600": 6, "dshot1200": 7,
}

# ESC firmware → best DShot protocol
ESC_FIRMWARE_TO_DSHOT = {
    "blheli_32": "dshot600",
    "blheli_s": "dshot300",
    "am32": "dshot600",
    "fettec": "dshot600",
    "kiss": "dshot600",
    "apm": "dshot600",
    "bluejay": "dshot300",
    "hwfly": "dshot600",
}

# ESC firmware → supports telemetry (for RPM filter)
ESC_SUPPORTS_TELEM = {
    "blheli_32", "am32", "fettec", "kiss", "apm",
}

# GPS chip patterns → GPS_TYPE
GPS_TYPE_MAP = {
    "u-blox": 1, "ublox": 1, "neo": 1, "m8n": 1, "m9n": 1, "m10": 1,
    "f9p": 1, "zed-f9p": 1,
    "nmea": 5,
    "sirf": 3,
    "msp": 19,
    "dronecan": 9, "uavcan": 9,
}

# Battery chemistry → voltage per cell thresholds
CHEMISTRY = {
    "lipo":  {"full": 4.20, "nominal": 3.70, "low": 3.50, "critical": 3.30},
    "li-po": {"full": 4.20, "nominal": 3.70, "low": 3.50, "critical": 3.30},
    "lihv":  {"full": 4.35, "nominal": 3.85, "low": 3.60, "critical": 3.40},
    "liion": {"full": 4.20, "nominal": 3.60, "low": 3.20, "critical": 2.80},
    "li-ion":{"full": 4.20, "nominal": 3.60, "low": 3.20, "critical": 2.80},
    "life":  {"full": 3.60, "nominal": 3.30, "low": 3.00, "critical": 2.80},
}

# PID starting points by prop size (inches) — from community tuning guides
PID_PRESETS = {
    # prop_size: (P, I, D) for roll/pitch — conservative starting point
    3:  (0.090, 0.090, 0.003),
    5:  (0.135, 0.135, 0.004),
    6:  (0.100, 0.100, 0.005),
    7:  (0.080, 0.080, 0.005),
    10: (0.050, 0.050, 0.006),
    13: (0.035, 0.035, 0.008),
}

# Yaw PID scaling relative to roll/pitch (typically 50-70% of roll P)
YAW_SCALE = 0.6


@dataclass
class ComponentSet:
    """Selected components for param generation."""
    frame: Optional[dict] = None
    fc: Optional[dict] = None
    esc: Optional[dict] = None
    motor: Optional[dict] = None
    battery: Optional[dict] = None
    gps: Optional[dict] = None
    platform_name: str = ""


@dataclass
class ParamFile:
    """Collects parameters before writing."""
    params: dict[str, tuple[float, str]] = field(default_factory=dict)

    def set(self, name: str, value: float, comment: str = ""):
        self.params[name] = (value, comment)

    def to_string(self) -> str:
        lines = [
            f"# ArduPilot Base Parameters — Generated by DroneClear Forge",
            f"# Generated: {datetime.utcnow().isoformat()}Z",
            f"# https://forgeprole.netlify.app",
            f"#",
            f"# IMPORTANT: This is a STARTING POINT. You must still:",
            f"#   1. Calibrate accelerometer and compass",
            f"#   2. Calibrate ESCs if using PWM protocol",
            f"#   3. Run initial hover test and check vibration levels",
            f"#   4. Use ArduPilot's AutoTune for final PID tuning",
            f"#   5. Verify failsafe behavior before flying away",
            f"#",
        ]
        current_prefix = ""
        for name in sorted(self.params.keys()):
            value, comment = self.params[name]
            prefix = name.split("_")[0] if "_" in name else name
            if prefix != current_prefix:
                current_prefix = prefix
                lines.append("")
            # Format value: integers as int, floats with appropriate precision
            if isinstance(value, float) and value == int(value) and abs(value) < 1e6:
                val_str = str(int(value))
            elif isinstance(value, float):
                val_str = f"{value:.6g}"
            else:
                val_str = str(value)
            line = f"{name},{val_str}"
            if comment:
                line = f"{line:<40} # {comment}"
            lines.append(line)
        return "\n".join(lines) + "\n"

    def write(self, path: Path):
        path.write_text(self.to_string(), encoding="utf-8")
        print(f"Wrote {len(self.params)} parameters to {path}")


# ── Database loading ─────────────────────────────────────────────────────────

def load_db(db_path: Path = DB_PATH) -> dict:
    return json.loads(db_path.read_text(encoding="utf-8"))


def find_component(db: dict, pid: str) -> Optional[dict]:
    """Find a component by PID across all categories."""
    for cat, items in db.get("components", {}).items():
        if not isinstance(items, list):
            continue
        for item in items:
            if item.get("pid") == pid:
                return item
    return None


def find_platform(db: dict, name: str) -> Optional[dict]:
    """Find a drone_model by name (case-insensitive partial match)."""
    name_lower = name.lower()
    for model in db.get("drone_models", []):
        if name_lower in model.get("name", "").lower():
            return model
    return None


def resolve_platform(db: dict, platform: dict) -> ComponentSet:
    """Resolve a platform's relations into a ComponentSet."""
    cs = ComponentSet(platform_name=platform.get("name", ""))
    rels = platform.get("relations", {})

    def first_pid(category: str) -> Optional[dict]:
        refs = rels.get(category, [])
        if refs and isinstance(refs, list):
            pid = refs[0].get("pid", "")
            return find_component(db, pid)
        return None

    cs.frame = first_pid("frames")
    cs.fc = first_pid("flight_controllers") or first_pid("stacks")
    cs.esc = first_pid("escs")
    cs.motor = first_pid("motors")
    cs.battery = first_pid("batteries")
    cs.gps = first_pid("gps_modules")
    return cs


# ── Parameter generation ─────────────────────────────────────────────────────

def generate_frame_params(pf: ParamFile, frame: dict):
    """Frame → FRAME_CLASS, FRAME_TYPE."""
    vtype = (frame.get("vehicle_type") or "quad").lower().replace(" ", "_")
    arm_cfg = (frame.get("arm_configuration") or "x").lower().replace(" ", "-")

    pf.set("FRAME_CLASS", FRAME_CLASS.get(vtype, 1),
           f"{frame.get('name', 'unknown')} — {vtype}")
    pf.set("FRAME_TYPE", FRAME_TYPE.get(arm_cfg, 1),
           f"arm config: {arm_cfg}")


def generate_battery_params(pf: ParamFile, battery: dict):
    """Battery → BATT_CAPACITY, BATT_MONITOR, voltage thresholds."""
    cells = battery.get("cell_count", 4)
    capacity = battery.get("capacity_mah", 1500)
    chem = (battery.get("chemistry") or "lipo").lower()
    thresholds = CHEMISTRY.get(chem, CHEMISTRY["lipo"])

    pf.set("BATT_MONITOR", 4, "Analog voltage + current")
    pf.set("BATT_CAPACITY", capacity,
           f"{capacity}mAh {cells}S {chem}")
    pf.set("BATT_ARM_VOLT", thresholds["nominal"] * cells * 0.95,
           "Min voltage to allow arming")
    pf.set("BATT_CRT_VOLT", thresholds["critical"] * cells,
           f"Critical: {thresholds['critical']}V/cell × {cells}S")
    pf.set("BATT_LOW_VOLT", thresholds["low"] * cells,
           f"Low: {thresholds['low']}V/cell × {cells}S")
    pf.set("BATT_FS_CRT_ACT", 1, "Land on critical voltage")
    pf.set("BATT_FS_LOW_ACT", 2, "RTL on low voltage")
    pf.set("BATT_FS_LOW_MAH", int(capacity * 0.20),
           "20% remaining capacity trigger")


def generate_esc_params(pf: ParamFile, esc: dict, motor: Optional[dict] = None):
    """ESC → MOT_PWM_TYPE, SERVO_DSHOT_*, harmonic notch config."""
    fw = (esc.get("esc_firmware") or "").lower().replace(" ", "_")
    interface = (esc.get("interface") or "").lower()

    # Determine best protocol
    if fw in ESC_FIRMWARE_TO_DSHOT:
        protocol = ESC_FIRMWARE_TO_DSHOT[fw]
    elif "dshot" in interface:
        protocol = "dshot600"
    else:
        protocol = "dshot300"

    pf.set("MOT_PWM_TYPE", PWM_TYPE.get(protocol, 6),
           f"{protocol} — ESC firmware: {fw or 'unknown'}")

    # RPM-based harmonic notch if ESC supports telemetry
    if fw in ESC_SUPPORTS_TELEM:
        pf.set("INS_HNTCH_ENABLE", 1, "Harmonic notch filter ON")
        pf.set("INS_HNTCH_MODE", 4, "RPM telemetry source (ESC telem)")
        pf.set("INS_HNTCH_OPTS", 2, "Double notch")
        pf.set("INS_HNTCH_REF", 1, "Reference value")
        # Estimate base frequency from motor KV if available
        if motor and motor.get("kv_rating"):
            kv = motor["kv_rating"]
            # Motor poles: infer from stator size (most FPV motors are 14-pole)
            poles = 14
            # Base freq at idle: roughly KV * Vbatt * (spin_min) * poles / 120
            # Simplified: 100-200 Hz for typical 5" quads
            base_freq = max(80, min(250, kv * 0.06))
            pf.set("INS_HNTCH_FREQ", round(base_freq),
                   f"Estimated from {kv}KV motor, {poles} poles")
        else:
            pf.set("INS_HNTCH_FREQ", 120, "Default — verify with FFT log")
    else:
        # Throttle-based notch fallback
        pf.set("INS_HNTCH_ENABLE", 1, "Harmonic notch filter ON")
        pf.set("INS_HNTCH_MODE", 1, "Throttle-based (no ESC telem)")
        pf.set("INS_HNTCH_OPTS", 2, "Double notch")
        pf.set("INS_HNTCH_FREQ", 120, "Default — verify with FFT log")
        pf.set("INS_HNTCH_REF", 0.35, "Hover throttle reference")


def generate_motor_params(pf: ParamFile, motor: dict, frame: Optional[dict] = None):
    """Motor → MOT_SPIN_*, MOT_THST_*, PID starting points."""
    kv = motor.get("kv_rating", 2000)
    prop_min = motor.get("prop_size_min_in", 5)
    prop_max = motor.get("prop_size_max_in", prop_min)
    prop_size = int((prop_min + prop_max) / 2)

    # MOT_SPIN_MIN/MAX depend on prop load — heavier props need higher min spin
    if prop_size <= 3:
        spin_min, spin_max = 0.12, 0.95
    elif prop_size <= 5:
        spin_min, spin_max = 0.15, 0.95
    elif prop_size <= 7:
        spin_min, spin_max = 0.12, 0.90
    else:
        spin_min, spin_max = 0.10, 0.85

    pf.set("MOT_SPIN_MIN", spin_min,
           f"{motor.get('name', '?')} — {kv}KV on {prop_size}\" props")
    pf.set("MOT_SPIN_MAX", spin_max, "Max throttle output")
    pf.set("MOT_SPIN_ARM", 0.05, "Arm spin speed")

    # Thrust expo — higher KV motors on small props are more linear
    if kv > 3000:
        expo = 0.55
    elif kv > 2000:
        expo = 0.60
    else:
        expo = 0.65
    pf.set("MOT_THST_EXPO", expo,
           f"Thrust curve linearization for {kv}KV")

    # Hover throttle estimate — rough function of KV and prop size
    # Lower KV + bigger props = lower hover throttle
    if prop_size >= 10:
        hover = 0.30
    elif prop_size >= 7:
        hover = 0.35
    elif prop_size >= 5:
        hover = 0.45 if kv < 2500 else 0.50
    else:
        hover = 0.55
    pf.set("MOT_HOVER_LEARN", 2, "Learn and save hover throttle")
    pf.set("MOT_THST_HOVER", hover,
           f"Starting estimate — hover learn will refine")

    # PID starting points
    p, i, d = PID_PRESETS.get(prop_size, PID_PRESETS[5])

    # Adjust for KV: high-KV motors are more responsive, need lower P
    kv_scale = max(0.7, min(1.3, 2000 / max(kv, 1)))

    rll_p = round(p * kv_scale, 4)
    rll_i = round(i * kv_scale, 4)
    rll_d = round(d * kv_scale, 5)

    pf.set("ATC_RAT_RLL_P", rll_p, f"{prop_size}\" props, {kv}KV — STARTING POINT")
    pf.set("ATC_RAT_RLL_I", rll_i, "Match to P")
    pf.set("ATC_RAT_RLL_D", rll_d, "Conservative — increase after test hover")
    pf.set("ATC_RAT_PIT_P", rll_p, "Symmetric with roll")
    pf.set("ATC_RAT_PIT_I", rll_i, "Symmetric with roll")
    pf.set("ATC_RAT_PIT_D", rll_d, "Symmetric with roll")
    pf.set("ATC_RAT_YAW_P", round(rll_p * YAW_SCALE, 4), "60% of roll P")
    pf.set("ATC_RAT_YAW_I", round(rll_i * YAW_SCALE * 0.5, 4), "Lower yaw I")
    pf.set("ATC_RAT_YAW_D", 0, "Yaw D typically 0")


def generate_gps_params(pf: ParamFile, gps: dict):
    """GPS → GPS_TYPE, serial assignment."""
    name_lower = (gps.get("name") or "").lower()
    interface = (gps.get("interface") or "").lower()

    # Detect GPS type
    gps_type = 1  # Default: u-blox (most common)
    for pattern, type_id in GPS_TYPE_MAP.items():
        if pattern in name_lower:
            gps_type = type_id
            break

    pf.set("GPS_TYPE", gps_type, gps.get("name", "GPS module"))
    pf.set("GPS_AUTO_CONFIG", 1, "Auto-configure GPS module")
    pf.set("GPS_GNSS_MODE", 67, "GPS+GLONASS+Galileo")
    pf.set("GPS_SAVE_CFG", 2, "Save to GPS flash")

    # Serial port for GPS — typically SERIAL3 in ArduPilot
    pf.set("SERIAL3_PROTOCOL", 5, "GPS")
    pf.set("SERIAL3_BAUD", 230, "230400 baud for u-blox")


def generate_fc_params(pf: ParamFile, fc: dict):
    """Flight controller → serial ports, IMU config, safety."""
    # Logging
    pf.set("LOG_BITMASK", 176126, "Default + IMU + PID + RCOUT")
    pf.set("LOG_BACKEND_TYPE", 1, "DataFlash")

    # INS settings based on IMU chip
    imu = (fc.get("imu") or "").upper()
    if "ICM42688" in imu:
        pf.set("INS_GYRO_RATE", 1, "ICM42688: 4kHz gyro rate")
    elif "BMI270" in imu:
        pf.set("INS_GYRO_RATE", 0, "BMI270: 1.6kHz gyro rate")

    # Standard serial config
    pf.set("SERIAL0_PROTOCOL", 2, "MAVLink2 on USB")
    pf.set("SERIAL0_BAUD", 115, "115200")
    pf.set("SERIAL1_PROTOCOL", 2, "MAVLink2 on TELEM1")
    pf.set("SERIAL1_BAUD", 57, "57600")
    pf.set("SERIAL2_PROTOCOL", -1, "Disabled (available)")


def generate_safety_params(pf: ParamFile):
    """Standard safety and failsafe parameters."""
    pf.set("ARMING_CHECK", 1, "All pre-arm checks enabled")
    pf.set("FS_THR_ENABLE", 1, "RC failsafe: RTL")
    pf.set("FS_THR_VALUE", 975, "PWM threshold for RC loss")
    pf.set("FS_GCS_ENABLE", 1, "GCS failsafe: RTL")
    pf.set("FS_CRASH_CHECK", 1, "Crash detection enabled")
    pf.set("FLTMODE1", 0, "Stabilize")
    pf.set("FLTMODE4", 2, "AltHold")
    pf.set("FLTMODE6", 6, "RTL")
    pf.set("RTL_ALT", 3000, "30m RTL altitude (cm)")
    pf.set("RTL_SPEED", 0, "Use WPNAV_SPEED for RTL")
    pf.set("WPNAV_SPEED", 800, "8 m/s cruise speed")
    pf.set("WPNAV_SPEED_DN", 250, "2.5 m/s descent")
    pf.set("WPNAV_SPEED_UP", 300, "3 m/s climb")


def generate_params(cs: ComponentSet) -> ParamFile:
    """Generate a complete .param file from a ComponentSet."""
    pf = ParamFile()

    # Header comment with build info
    if cs.platform_name:
        pf.params["# Platform"] = (0, cs.platform_name)

    if cs.frame:
        generate_frame_params(pf, cs.frame)
    else:
        pf.set("FRAME_CLASS", 1, "Quad (default — no frame specified)")
        pf.set("FRAME_TYPE", 1, "X layout")

    if cs.battery:
        generate_battery_params(pf, cs.battery)

    if cs.esc:
        generate_esc_params(pf, cs.esc, cs.motor)

    if cs.motor:
        generate_motor_params(pf, cs.motor, cs.frame)
    else:
        # Sensible defaults if no motor specified
        pf.set("MOT_SPIN_MIN", 0.15, "Default — no motor specified")
        pf.set("MOT_SPIN_MAX", 0.95, "Default")

    if cs.gps:
        generate_gps_params(pf, cs.gps)

    if cs.fc:
        generate_fc_params(pf, cs.fc)

    generate_safety_params(pf)

    # Remove the fake header entry
    pf.params.pop("# Platform", None)

    return pf


# ── CLI ───────────────────────────────────────────────────────────────────────

def main():
    import argparse

    ap = argparse.ArgumentParser(
        description="Generate ArduPilot .param file from Forge components")
    ap.add_argument("--frame", help="Frame PID (e.g. FRM-1005)")
    ap.add_argument("--fc", help="Flight controller PID (e.g. FC-1000)")
    ap.add_argument("--esc", help="ESC PID (e.g. ESC-1001)")
    ap.add_argument("--motor", help="Motor PID (e.g. MTR-1000)")
    ap.add_argument("--battery", help="Battery PID (e.g. BAT-1009)")
    ap.add_argument("--gps", help="GPS module PID (e.g. GPS-1009)")
    ap.add_argument("--build", help="Platform name (looks up components from relations)")
    ap.add_argument("--output", "-o", default=None,
                    help="Output .param file (default: stdout)")
    ap.add_argument("--list-platforms", action="store_true",
                    help="List all platforms with component relations")
    ap.add_argument("--db", default=str(DB_PATH),
                    help="Path to forge_database.json")
    args = ap.parse_args()

    db = load_db(Path(args.db))

    if args.list_platforms:
        for m in db.get("drone_models", []):
            rels = m.get("relations", {})
            part_count = sum(len(v) for v in rels.values() if isinstance(v, list))
            if part_count >= 2:
                print(f"  {m['name']:<45} {part_count} components")
        return

    if args.build:
        platform = find_platform(db, args.build)
        if not platform:
            print(f"Platform '{args.build}' not found. Use --list-platforms to see available.", file=sys.stderr)
            sys.exit(1)
        cs = resolve_platform(db, platform)
        print(f"Platform: {platform['name']}", file=sys.stderr)
        for label, comp in [("Frame", cs.frame), ("FC", cs.fc), ("ESC", cs.esc),
                            ("Motor", cs.motor), ("Battery", cs.battery), ("GPS", cs.gps)]:
            name = comp.get("name", "—") if comp else "—"
            print(f"  {label:<10} {name}", file=sys.stderr)
    else:
        cs = ComponentSet()
        if args.frame:
            cs.frame = find_component(db, args.frame)
        if args.fc:
            cs.fc = find_component(db, args.fc)
        if args.esc:
            cs.esc = find_component(db, args.esc)
        if args.motor:
            cs.motor = find_component(db, args.motor)
        if args.battery:
            cs.battery = find_component(db, args.battery)
        if args.gps:
            cs.gps = find_component(db, args.gps)

    pf = generate_params(cs)

    if args.output:
        pf.write(Path(args.output))
    else:
        print(pf.to_string())


if __name__ == "__main__":
    main()
