import { projectDataset } from './forge-data-projections.mjs';

/**
 * forge-data — Cloudflare Worker route for /api/data?type=<dataset>
 *
 * GET  — serve JSON from PIE_OUTPUTS / PIE_DB, then static assets as fallback.
 * POST — authenticated admin write.
 *
 * Core public intelligence-lens datasets are freshness-gated. Stale KV or
 * static fallback data returns HTTP 503 instead of silently presenting old
 * analysis as current.
 *
 * Large evidence and coverage artifacts support bounded read-only projections:
 *   ?type=article_event_clusters&view=summary
 *   ?type=article_event_clusters&actor=Russia%20%2F%20Mil&offset=0&limit=20
 *   ?type=article_event_clusters&event_id=EVT-...
 *   ?type=source_coverage_matrix&view=summary
 *   ?type=source_coverage_matrix&view=sources&offset=0&limit=50
 *   ?type=source_coverage_matrix&source=united24
 */

const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization',
};

const NO_CACHE = {
  'Cache-Control': 'no-store, max-age=0',
  'CDN-Cache-Control': 'no-store',
};

// These artifacts are regenerated by the software-only Ai-Project cascade.
// A 72-hour limit tolerates a missed daily run without allowing a weeks-old
// analytic ranking, event grouping, or coverage statement to appear current.
const FRESHNESS_LIMIT_MS = new Map([
  ['adversary_bom', 72 * 60 * 60 * 1000],
  ['component_mirroring_index', 72 * 60 * 60 * 1000],
  ['sanctions_evasion_graph', 72 * 60 * 60 * 1000],
  ['actor_fingerprints', 72 * 60 * 60 * 1000],
  ['article_event_clusters', 72 * 60 * 60 * 1000],
  ['source_coverage_matrix', 72 * 60 * 60 * 1000],
  ['ttp_counter_gap', 72 * 60 * 60 * 1000],
  ['threat_scores', 72 * 60 * 60 * 1000],
  ['dataset_catalog', 72 * 60 * 60 * 1000],
]);

function resp(data, status = 200, extraHeaders = {}) {
  return new Response(JSON.stringify(data), {
    status,
    headers: {
      ...CORS,
      ...NO_CACHE,
      'Content-Type': 'application/json; charset=utf-8',
      ...extraHeaders,
    },
  });
}

function generatedAtOf(data) {
  const raw = data && data.meta && data.meta.generated_at;
  if (typeof raw !== 'string' || !raw.trim()) return null;
  const timestamp = Date.parse(raw);
  return Number.isFinite(timestamp) ? timestamp : null;
}

function freshnessOf(data, type, source) {
  const generatedAt = generatedAtOf(data);
  const now = Date.now();
  const maxAgeMs = FRESHNESS_LIMIT_MS.get(type) || null;
  const ageMs = generatedAt == null ? null : Math.max(0, now - generatedAt);

  return {
    source,
    generated_at:
      generatedAt == null ? null : new Date(generatedAt).toISOString(),
    checked_at: new Date(now).toISOString(),
    age_seconds: ageMs == null ? null : Math.floor(ageMs / 1000),
    max_age_seconds:
      maxAgeMs == null ? null : Math.floor(maxAgeMs / 1000),
    status:
      maxAgeMs == null
        ? 'not-gated'
        : generatedAt == null
          ? 'unknown'
          : ageMs > maxAgeMs
            ? 'stale'
            : 'fresh',
  };
}

function serveParsed(data, type, source, params) {
  // Freshness and semantic publication controls are evaluated against the
  // complete source document before any summary, actor, source, or event
  // projection is made.
  const freshness = freshnessOf(data, type, source);
  const maxAgeMs = FRESHNESS_LIMIT_MS.get(type);

  if (
    maxAgeMs != null &&
    (freshness.generated_at == null || freshness.status === 'stale')
  ) {
    return resp(
      {
        error: `Dataset ${type} is stale or missing a valid generated_at timestamp`,
        type,
        source,
        freshness,
        action:
          'The publication gate withheld this analytic dataset. Regenerate and validate the Ai-Project public-data pipeline.',
      },
      503,
      {
        'Retry-After': '3600',
        'X-Data-Source': source,
        'X-Data-Freshness': freshness.status,
      },
    );
  }

  let projected;
  try {
    projected = projectDataset(data, type, params);
  } catch (error) {
    if (error && error.code === 'DATASET_PUBLICATION_CONTROL') {
      return resp(
        {
          error: `Dataset ${type} failed semantic publication controls`,
          type,
          source,
          freshness,
          validation_errors: error.validationErrors || [],
          action:
            'The publication gate withheld this dataset because its provenance, schema, or safety controls did not match the supported public contract.',
        },
        503,
        {
          'Retry-After': '3600',
          'X-Data-Source': source,
          'X-Data-Freshness': freshness.status,
          'X-Data-Publication': 'withheld',
        },
      );
    }
    throw error;
  }

  return resp(
    {
      data: projected,
      tier: 'free',
      type,
      source,
      freshness,
    },
    200,
    {
      'X-Data-Source': source,
      'X-Data-Freshness': freshness.status,
      'X-Data-Publication': 'validated',
    },
  );
}

function parseAndServe(raw, type, source, params) {
  try {
    return serveParsed(JSON.parse(raw), type, source, params);
  } catch (error) {
    return resp(
      {
        error: `Dataset ${type} contains invalid JSON`,
        type,
        source,
        detail: error instanceof Error ? error.message : String(error),
      },
      500,
      { 'X-Data-Source': source },
    );
  }
}

const DATASETS = new Set([
  'forge_database',
  'drone_database',
  'topic_component_map',
  'forge_firmware_versions',
  'forge_troubleshooting',
  'forge_incompatibilities',
  'miner_health',
  'miner_registry',
  'dataset_catalog',
  'source_coverage_matrix',
  'intel_articles',
  'intel_companies',
  'intel_platforms',
  'intel_programs',
  'pie_flags',
  'pie_brief',
  'pie_brief_history',
  'pie_predictions',
  'pie_trends',
  'pie_weekly',
  'predictions_best',
  'predictions_archive',
  'llm_predictions',
  'gap_analysis_latest',
  'entity_graph',
  'forge_intel',
  'commercial_master',
  'solicitations',
  'federal_awards',
  'sam_watchlist',
  'dfr_master',
  'defense_master',
  'flags',
  'predictions',
  'adversary_bom',
  'component_mirroring_index',
  'sanctions_evasion_graph',
  'actor_fingerprints',
  'article_event_clusters',
  'ttp_counter_gap',
  'threat_scores',
  'market_lens',
  'prediction_outcomes',
  'calibration_scores',
  'pie_delta',
  'clock_score',
  'ddg2',
  'ddg1',
  'github_hwdef',
  'sanctions_lists',
  'gleif_entities',
  'wikidata_entities',
  'gdelt_events',
  'conference_exhibitors',
  'uspto_marks',
  'usajobs',
  'comtrade_data',
]);

const PIE_OUTPUTS_KEYS = new Set([
  'pie_flags',
  'pie_brief',
  'pie_brief_history',
  'pie_predictions',
  'pie_trends',
  'pie_weekly',
  'predictions_best',
  'predictions_archive',
  'llm_predictions',
  'gap_analysis_latest',
  'entity_graph',
  'forge_intel',
  'intel_articles',
  'intel_companies',
  'intel_platforms',
  'intel_programs',
  'miner_health',
  'miner_registry',
  'dataset_catalog',
  'source_coverage_matrix',
  'solicitations',
  'federal_awards',
  'sam_watchlist',
  'flags',
  'predictions',
  'adversary_bom',
  'component_mirroring_index',
  'sanctions_evasion_graph',
  'actor_fingerprints',
  'article_event_clusters',
  'ttp_counter_gap',
  'threat_scores',
  'market_lens',
  'prediction_outcomes',
  'calibration_scores',
  'pie_delta',
  'clock_score',
  'ddg2',
  'ddg1',
  'github_hwdef',
  'sanctions_lists',
  'gleif_entities',
  'wikidata_entities',
  'gdelt_events',
  'conference_exhibitors',
  'uspto_marks',
  'usajobs',
  'comtrade_data',
]);

export default {
  async fetch(request, env) {
    if (request.method === 'OPTIONS') {
      return new Response(null, { status: 204, headers: CORS });
    }

    const url = new URL(request.url);
    const type = url.searchParams.get('type') || '';

    if (request.method === 'POST') {
      const adminKey = env.FORGE_BLOBS_ADMIN_KEY;
      const provided = (
        request.headers.get('authorization') || ''
      ).replace(/^Bearer\s+/i, '');

      if (!adminKey) {
        return resp(
          { error: 'FORGE_BLOBS_ADMIN_KEY not configured' },
          503,
        );
      }
      if (provided !== adminKey) {
        return resp({ error: 'Invalid admin key' }, 401);
      }
      if (!type || !DATASETS.has(type)) {
        return resp({ error: `Unknown dataset: ${type}` }, 404);
      }

      try {
        const body = await request.text();
        if (!body || body.length < 2) {
          return resp({ error: 'Empty body' }, 400);
        }

        let parsed;
        try {
          parsed = JSON.parse(body);
        } catch (error) {
          return resp(
            {
              error:
                'Invalid JSON: ' +
                (error instanceof Error ? error.message : String(error)),
            },
            400,
          );
        }

        const freshness = freshnessOf(parsed, type, 'admin-write');
        if (
          FRESHNESS_LIMIT_MS.has(type) &&
          freshness.generated_at == null
        ) {
          return resp(
            {
              error:
                `Dataset ${type} requires a valid meta.generated_at timestamp`,
              freshness,
            },
            400,
          );
        }

        // Semantic controls are also checked before accepting a current public
        // artifact into KV; a successful write means projections can be made
        // from the stored document without weakening the publication contract.
        try {
          projectDataset(parsed, type, new URLSearchParams({ view: 'method' }));
        } catch (error) {
          if (error && error.code === 'DATASET_PUBLICATION_CONTROL') {
            return resp(
              {
                error: `Dataset ${type} failed semantic publication controls`,
                validation_errors: error.validationErrors || [],
              },
              400,
            );
          }
          throw error;
        }

        const kv = PIE_OUTPUTS_KEYS.has(type)
          ? env.PIE_OUTPUTS
          : env.PIE_DB;
        await kv.put(type, body);

        return resp({
          ok: true,
          type,
          size: body.length,
          freshness,
          message: `${type} written to KV (${body.length} bytes)`,
        });
      } catch (error) {
        return resp(
          {
            error:
              'KV write failed: ' +
              (error instanceof Error ? error.message : String(error)),
          },
          500,
        );
      }
    }

    if (!type) {
      return resp(
        {
          error: 'type parameter required',
          available: Array.from(DATASETS),
        },
        400,
      );
    }
    if (!DATASETS.has(type)) {
      return resp({ error: `Unknown dataset: ${type}` }, 404);
    }

    try {
      const kv = PIE_OUTPUTS_KEYS.has(type)
        ? env.PIE_OUTPUTS
        : env.PIE_DB;
      const raw = await kv.get(type);
      if (raw) {
        return parseAndServe(raw, type, 'kv', url.searchParams);
      }
    } catch (error) {
      console.error(
        `[forge-data] KV error for ${type}:`,
        error instanceof Error ? error.message : String(error),
      );
    }

    // Static fallback is useful for availability, but the same freshness and
    // semantic gates apply. Old or unsafe bundled JSON is never silently
    // labeled current.
    try {
      for (const tryPath of [
        `/${type}.json`,
        `/static/${type}.json`,
      ]) {
        try {
          const staticUrl = new URL(request.url);
          staticUrl.pathname = tryPath;
          staticUrl.search = '';
          const staticResponse = await env.ASSETS.fetch(
            new Request(staticUrl.toString()),
          );
          if (staticResponse.ok) {
            const raw = await staticResponse.text();
            return parseAndServe(
              raw,
              type,
              `static:${tryPath}`,
              url.searchParams,
            );
          }
        } catch {
          // Try the next static path.
        }
      }
    } catch {
      // ASSETS may be absent in local worker tests.
    }

    return resp(
      { error: `Dataset ${type} not available`, type },
      404,
    );
  },
};
